### ISSUE TITLE
Merging in user configuration

### ISSUE THREAD

**Issue by rmvangun** [localstack/pulumi-local#12]
Would it be in scope for this project to merge existing Pulumi config with the localstack config? The functionality would be such that if a user provided a `--config-file` argument to `pulumilocal`, it would merge that with the `Pulumi.localstack.yaml` file.

I'm pretty new to Pulumi so wonder if I'm overlooking another way to do this.

**Comment by whummer** [comment]
Hi @rmvangun , thanks for the suggestion. I think that could definitely make sense - do you think you could help with creating a draft pull request with this change? Even a first draft PR would help, we could then help push it over the line.. 👍 That would be awesome, and much appreciated. 🙌

**Comment by lakkeger** [comment]
Hi @rmvangun!
This feature is still not implemented yet. We'd put it on a timeline and getting back to you with a fix. Thanks for your patience in advance.
