### ISSUE TITLE
Request to change Python package name from Pulumi

### ISSUE THREAD

**Issue by AaronFriel** [localstack/pulumi-local#13]
Hey folks, @whummer, @thrau et al.,

We at Pulumi attempted to publish a `pulumi-local` provider [github.com/pulumi/pulumi-local](https://github.com/pulumi/pulumi-local) but we ran into an issue on publishing to PyPI due to the name collision.

Would it be feasible to discuss a name change? We use `pulumi-X` to denote a package that manages resources for X. In this case, local is a provider that manages local file content, and we've already acquired the package names for NPM and NuGet.

**Comment by thrau** [comment]
Hey @AaronFriel! I appreciate the request, I'll get this back to the team to discuss. Obviously we don't want to block you or squat something that's clearly associated with your brand. On the other hand we need to look into what it means to transfer ownership of a pypi package for our users. It's frankly a pretty big deal to replace a pypi package with a completely different software. But we're happy to work together on this and find consensus.

**Comment by AaronFriel** [comment]
@thrau totally understand and I don't want to use the "s" word to describe this. PyPI lacks namespacing, so we have to cooperate in the global namespace and we can't very well reserve every `pulumi-` package name, that would shut out community packages. 

We'll hold off on publishing a Python package for the Local provider for now. If I might suggest, `localstack-pulumi` would be a good rename, leaving the door open if for example you wanted to publish a `pulumi-localstack` provider!

**Comment by thrau** [comment]
Hey @AaronFriel. After discussing with the team, we have concluded that we cannot transfer ownership of pulumi-local right now.

As you pointed out, given the lack of namespaces in pypi, we would effectively replace unsuspecting user's `pulumilocal` command with a completely different software. Not only is this extremely inconvenient to users, but it would also erode trust in our software supply chain if we do this without a long deprecation/warning period. There are still a decent number of downloads and we have no reliable way of notifying users of the package in the short term. Moreover, pypi does not allow overwriting existing versions and releases (for good reason).

Having said all that, we are interested in finding a solution to this, and maybe we can collaborate together on finding a deprecation path + a better integration between pulumi and localstack, so we could make pulumi-local obsolete all together at some point. I suggest we take that discussion to another channel though.

**Comment by lakkeger** [comment]
Hi!
Archiving this issue as the discussion has staled.
