### ISSUE TITLE
[Feature request] Using local filesystem by default

### ISSUE THREAD

**Issue by andreujuanc** [localstack/pulumi-local#14]
Hi,

I was going to do all this setup by hand, and found this this (gratefully!)
I was thinking that maybe the default behaviour for a localstack deployment should be using  --local https://www.pulumi.com/docs/concepts/state/#local-filesystem or a file://<dir> backend

This would make more sense as a lot of people will not persist their localstack environments (for example, i use it in a docker-compose service)

Cheers

**Comment by cabeaulac** [comment]
Hi @andreujuanc . 
If you set your `PULUMI_BACKEND_URL` to something like `file:///Users/andre/localdev/pulumi-state` then you will get what you want. There is no need to run `pulumi login` when you use PULUMI_BACKEND_URL and PULUMI_CONFIG_PASSPHRASE.

For example 
## Set your PULUMI_BACKEND_URL
```
export PULUMI_BACKEND_URL=file:///Users/andre/localdev/pulumi-state
```
## Set your PULUMI_CONFIG_PASSPHRASE
```
PULUMI_CONFIG_PASSPHRASE=andre123
```
## Create a stack called dev
```
pulumilocal stack select -c dev --non-interactive
```
## Deploy the stack
```
pulumilocal up
```

**Comment by lakkeger** [comment]
Hi @andreujuanc!
As @cabeaulac have stated the behaviour is easily modifiable, however the README is not reflecting/highlighting this enough. We plan to add some extra clarification in the near future in regards to this.
