### ISSUE TITLE
`pulumilocal` does not work on Windows

### ISSUE THREAD

**Issue by thomasmansencal** [localstack/pulumi-local#30]
Hello,

I was giving a test drive a `pulumi` / `pulumi-local` with *LocalStack* but out-of-the-box, the wrapper does not work:

```
PS D:\Development\pulumi-ramblings> pulumilocal up
Updating this Stack with LocalStack config
[WinError 2] The system cannot find the file specified
```

Removing all the `executable=PULUMI_CMD` in the subprocess calls did the job:

```
subprocess.run(executable=PULUMI_CMD, ...
```
to

```
subprocess.run(...
```

I know that there are [platform dependent subtleties](https://docs.python.org/3/library/subprocess.html#popen-constructor) but I never had to pass the `executable` argument on Windows if the executable itself is already present in the args passed to `POpen` et al.

**Comment by lakkeger** [comment]
Hi @KelSolaar,
Thanks for reporting this issue. As a current workaround, could you please set the `PULUMI_CMD` env variable in your shell to the absolute path of your pulumi executable and rerun your command and share the output?
