### ISSUE TITLE
Error when `pulumilocal up` for the first time, when creating `localstack` stack

### ISSUE THREAD

**Issue by bolinocroustibat** [localstack/pulumi-local#4]
When doing `pulumilocal up` for the first time on a project, one gets:

`warning: Error downloading plugin: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-local-v0.3.0-darwin-amd64.tar.gz```

**Comment by lakkeger** [comment]
Hi @bolinocroustibat,
The above message is related to Pulumi itself, so unfortunately we have no control on this.
I'd recommend to raise the issue with Pulumi itself.

Closing the issue as won't fix.
