### ISSUE TITLE
Provide missing key names in error messages

### ISSUE THREAD

**Issue by ToddG** [localstack/pulumi-local#7]
**WHAT**
Provide better error messages, specifically missing keys.

**WHY**
I spent about 4 hours tracking down this issue.
Another user spent a significant amount of time as well, see: https://github.com/localstack/pulumi-local/issues/5

**HOW**
Rather than emitting an opaque message such as:

```
  aws:s3:Bucket (my-bucket):
    error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key
```

Actually emit the _name of the key_, like this:

```
  aws:s3:Bucket (my-bucket):
    error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key: INVALID_OR_UNKNOWN_KEY_NAME_HERE
```

**Comment by ToddG** [comment]
See thread on this here: https://pulumi-community.slack.com/archives/C026EE6N2VB/p1668542984295379

**Comment by ToddG** [comment]
Created issue in `pulumi` here: https://github.com/pulumi/pulumi-terraform-bridge/issues/651

**Comment by lakkeger** [comment]
Hi @ToddG!
Unfortunately as you've tracked it down already this error message is provided by Pulumi itself we just displaying it.

Closing this issue.
