### ISSUE TITLE
Constraint on `up` cmd causes localstack file creation on other pulumi cmds

### ISSUE THREAD

**Issue by chrisfentiman** [localstack/pulumi-local#9]
**Description:**

Pulumilocal restricts the stack option to the up command, which creates issues if you're trying to debug different stacks using different commands. `pulumilocal` should respect the stack if it is set regardless of the command.

**Steps to reproduce:**

1. Create a localstack stack named `Pulumi.local.yaml.`
2. Run `pulumilocal preview -s local`
3. Observe `pulumilocal` create a new `Pulumi.localstack.yaml`, and use the newly created stack instead of the specified stack.

**Expected Behavior:**

- The specified stack should be used by `pulumilocal` and not create a new "localstack" stack.

**Notes:**

- Inspecting the code, I can see on line [L375](https://github.com/localstack/pulumi-local/blob/b59b269a6c19d3ec41a596ec59d0a30cc9691c69/bin/pulumilocal#L375) the conditional is restricted to checking the `up` command, making every other command that specifies a stack useless. Also, it only checks for `-s` even though `--stack` is also a valid option. 
- For background, running a simple `preview` command (which I expect most people do) using pulumilocal creates a new local stack file, which becomes problematic when trying to debug stack issues for a specific setup without actually deploying. It requires we delete the real localstack file, to rename another file to "Pulumi.localstack.yaml" just to get it working.
- Finally, we use pulumilocal because it is a safeguard; we do not want people making a mistake in our development environment (even though we have other securities in place), and this package makes it easy to ensure anyone working locally always deploys locally.

**Action:**
- I can open a PR to fix this if you can confirm this wasn't done for some specific reason I cannot see.

**Comment by whummer** [comment]
Hi @chrisfentiman , thanks for reporting, and apologies for the long delay. 

Great analysis! Indeed, agreed that the specified stack should be used by `pulumilocal` directly, if possible. 👍 

>  I can open a PR to fix this if you can confirm this wasn't done for some specific reason I cannot see.

This would be awesome, and much appreciated. We don't currently have a proper test setup, but ideally it would be great if we could also cover it with an integration test. Happy to help out with that piece though, if you could give it a go with a draft PR for the functionality itself.. Thanks for your help! 🙌

**Comment by lakkeger** [comment]
Hi @chrisfentiman!
The above mentioned issue seems to be already resolved on the current version (v1.2.0).

Closing this issue.
